dist: focal
language: node_js
node_js: stable

before_install:
  - echo "BEFORE-INSTALL"

install:
  - npm ci

script:
  - echo "MAIN SCRIPT"

jobs:
  allow_failures:
  include:
    - stage: echo "FIRST STAGE IN BUILD (stage 1)"
      script: echo "FIRST SCRIPT IN STAGE 1"
    - stage: echo "SECOND STAGE IN BUILD (stage 2)"
      script: echo "FIRST SCRIPT IN STAGE 2"
    - script: echo "FINAL SCRIPT"
